### ISSUE TITLE
Remove protocol specification from script src

### ISSUE THREAD

**Issue by serdyuk-alex** [PaesslerAG/django-rosetta-grappelli#9]
Can you remove protocol in src attribute here:
https://github.com/PaesslerAG/django-rosetta-grappelli/blob/56f2954750ca07adddce9425333a63d0112598a7/rosetta-grappelli/templates/rosetta/base.html#L18

When site protocol is https it fails to load the script:
```diff
- (index):1 Mixed Content: The page at 'https://<domain>/rosetta/' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/jsapi'. This request has been blocked; the content must be served over HTTPS.
```
Thanks

**Comment by belugame** [comment]
closed in https://github.com/PaesslerAG/django-rosetta-grappelli/pull/8
